import { ThemeProvider } from "@/components/theme-provider";
import { Poppins } from "next/font/google";
import { PropsWithChildren } from "react";
import { Component } from "@/lib/types";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

const Layout: Component<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "antialiased dark:bg-[#171616] dark:text-white")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 border-x border-neutral-200 dark:border-neutral-800">
              <div className="sticky hidden md:block top-0 z-50 h-3" />
              <main className="max-w-2xl mx-auto">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}


export default Layout;