-- CreateEnum
CREATE TYPE "LockedType" AS ENUM ('TEMPORARY', 'PERMANENT');

-- CreateEnum
CREATE TYPE "LockedReason" AS ENUM ('HARMFUL_CONTENT', 'HARASSMENT', 'HATE_SPEECH', 'IMPERSONATION', 'SPAM', 'INAPPROPRIATE_CONTENT', 'MULTIPLE_VIOLATIONS', 'SECURITY_CONCERNS', 'BANNED_IP', 'HARMFUL_AUTOMATION', 'FAKE_ENGAGEMENT', 'ILLEGAL_CONTENT', 'UNDERAGE', 'TRADEMARK_VIOLATION', 'COPYRIGHT_VIOLATION', 'PLATFORM_MANIPULATION', 'INVESTIGATION_PENDING');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "locked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lockedAt" TIMESTAMP(3),
ADD COLUMN     "lockedUntil" TIMESTAMP(3);
